version: "3.8"
services:
  react-app:
    build: .
    ports:
      - "9090:80"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
